language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew check --info
  - ./gradlew -p sample check --info
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master

notifications:
  email: true

